config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount Monologue::Engine, at: '/blog'
  get 'home' => 'home#index', as: :home
  post 'home/create' => 'home#create'
  get 'services' => 'home#services', as: :services
  get 'about' => 'home#about', as: :about
  get 'shop' => 'home#shop', as: :shop

  root 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_action :authenticate_user!
  def index
  end

  def services
  end

  def about
  end

  def shop
  end

  def blog
  end

  #sends email
  def create
    user_email = params["email"]
    user_name = params["name"]
    # ContactMailer.user_contact(user_email, user_name).deliver
    redirect_to home_path, notice: "Thank you for contacting me, I'll be in touch shortly."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end

end

app/views/home/about.html.haml
.container.l-container
  %h3.text-center.page-header.text-muted About Me
  .row
    .col-md-12
      .media.about-content
        %a.media-left{href: "#"}
          =image_tag 'benefit.png', :class => 'media-object', :height=>240, :width=>240
        .media-body
          %h4.media-heading Interior Designer / Party Planner / Idea Person
          %p.lead
            Hi I am Neisha, the owner and principal designer of Niche Interiors and Events.
            I like to refer to myself as an “Accommodation Specialist”, since I take great pride in creating
            beautiful spaces that are also functional and personalized to the needs of my clients.
          %p
            With an extensive background in Supply Chain, I am also well versed in sourcing and vendor relations,
            which contributes greatly to my ability to satisfy challenging demands and budgets.
          %p
            Besides Interior Design, I am also passionate about nature, history and food.
            In my spare time, I enjoy activities such as browsing design and architectural catalogues, as well as taking long walks around furniture showrooms. 

app/views/home/blog.html.haml
.container.l-container
  %h3.text-center.text-muted
    The Blog
  %p
    I will be sharing tips on desiging, planning and organization. 
    Coming Soon...

app/views/home/index-old1.html.haml
.jumbotron.text-xs-center
  .container
    -# %h1 Home controller
    .row
      .col-sm-12
        .l-logo
          =image_tag 'logo.png', :class => 'logo img-responsive'
        %h1.jumbotron-heading
          Niche Interior Designs
        %p.lead.text-muted
          Coming Soon...

app/views/home/index.html.haml
.container.l-container
  -# %h1 Home controller
  .row
    .col-sm-12.text-center
      .l-logo
        =image_tag 'logo.png', :class => 'logo img-responsive'
  %h1.text-center.call-out
    Ambitious Projects require Disruptive Thinking
  -# %hr

  %p.secondary-callout.lead.text-center
    Let me take your projects to the next level. <b>Interior Design</b>, <b>Space Planning/Layout</b>,
    <b>Event Space Design</b> & <b>Shopping</b>;
    I will provide insights and experience needed for
    a successful project. Send me a quick hello below and <b>get my free ebook</b> on simple ways to improve
    your life through design.

%hr
  
.container
  %p.lead.text-uppercase.benefits.text-center Why Niche?
  %h3.text-center Here's why you should use Niche-ie designs

.container-fluid.l-benefit.benefits_alt
  .container.l-container
    .media
      %a.media-left{:href => "#"}
        =image_tag 'benefit.png', :class => 'media-object', :height=>240, :width=>240
      .media-body
        %h3.media-heading.text-center Specialized
        %p.benefits-text
          “Home is where the heart is”. It should therefore be your happy and special place.
          Niche incorporates practices and pieces to ensure that your home is exactly that.
          We work with each client on a personalized level, taking into account your LIFESTYLE- First your LIFE and what it consists of- cultural,
          social and spiritual, and the ways in which your home can be modified to provide a more special and inspiring space.

.container-fluid
  .container.l-container
    .media
      .media-body
        %h3.media-heading.text-center Stylish
        %p.benefits-text
          Then there is your personal STYLE, what are your likes and how can they be incorporated to make your home as beautiful as you are.
          Niche delivers one of a kind designs that often includes custom, Chic and carefully curated pieces, as well as unique arrangements that will definitely make your home inviting, pretty and practical.
          Sourcing from local and small businesses are other ways in which we aim to deliver more personalized designs
      %a.media-right{:href => "#"}
        =image_tag 'benefit.png', :class => 'media-object', :height=>240, :width=>240

.container-fluid.l-benefit.benefits_alt
  .container.l-container
    .media
      %a.media-left{:href => "#"}
        =image_tag 'benefit.png', :class => 'media-object', :height=>240, :width=>240
      .media-body
        %h3.media-heading.text-center Savvy
        %p.benefits-text
          Designing a space can be quite a challenge, Niche has the expertise and professionalism to simplify the process by providing
          solutions to the most complex dilemma. We respect our client’s needs and will therefore make all attempts to be as resourceful as possible,
          by strategically sourcing and planning your space in order to operate within budget and time constraints. We also seek earthly balances by being socially responsible to the best of our abilities- all attempts are made to incorporate environmentally safe practices and products into our designs

.container-fluid.cta
  .l-cta
    %h2.text-center
      Reach out to learn more.
    %p.text-center
      As a bonus, you'll receive my free interior design ebook!
    =form_tag('/home/create', method: :post) do
      %fieldset.form-group
        =text_field_tag 'name', nil, placeholder: 'Your Name', class: 'form-control'
      %fieldset.form-group
        =email_field_tag 'email', nil, placeholder: 'Your Email', class: 'form-control'
      %fieldset.form-group
        =text_area_tag 'comment', nil, placeholder: 'Optional', class: 'form-control'
      =submit_tag "Submit", class: 'btn btn-primary text-center pull-right'

app/views/home/services.html.haml
.container.l-container
  %h3.text-center.page-header.text-muted Services
  .row
    .col-md-12
      %h5 Interior Design
      %p
        Our design and styling services include a thorough consultation and covers every aspect of the project up until completion. Timeline and budget schedules are also provided to ensure transparency and accountability throughout.
        We have an extensive directory of suppliers and vendors who are able to source the best and most unique items for your home.

      %hr

      %h5 Space Planning and Organization Consulting
      %p
        The layout and size of a space are often very challenging to work around.
        Niche Decor offers planning and organizing services that convert troublesome spaces into usable ones.
      %p
        We also provide organization services to help increase the efficiency of your space and time.
        From closets, office spaces and various other work areas, we provide the solutions to get rid of the mess.

      %hr

      %h5 Event Design
      %p
        Weddings and other Special Occasions- the room sets the mood!
        Our unique and targeted designs will assist with you and your guest having a great time, as well as a lasting impression.

      %hr

      %h5 Shopping
      %p
        If all you need is a helping hand to assist with shopping, we have plenty and also love to shop.
        A new home or renovation calls for furnishings and finishes that you may just not have the time to source. Niche Decor will assess your needs and deliver them to you.

app/views/home/shop.html.haml
.container.l-container
  %h3.text-center.text-muted
    Coming Soon...

app/views/layouts/application-old.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Niche
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    =render 'shared/header'
    .container.l-container
      .row
        .col-md-12
          =flash_messages
    = yield
    =render 'shared/footer'

app/views/layouts/application-old1.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Niche
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Niche
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    =render 'shared/header'
    .container.l-container
      .row
        .col-md-12
          =flash_messages
    = yield
    =render 'shared/footer'

app/views/shared/_footer.html.haml
%footer.l-footer
  .container.text-muted
    &copy; Niche-ie Designs, 2015; All Rights Reserved

app/views/shared/_header.html.haml
%header.l-header

  %nav.navbar.navbar-fixed-top.header-bg
    .container
      .navbar-header
        %button.navbar-toggler.hidden-sm-up{:type => "button", :"data-toggle" => "collapse", :"data-target"=>"#niche-nav"}
          ☰
        -# %a.navbar-brand{:href => "#"} Niche
      #niche-nav.collapse.navbar-collapse.navbar-toggleable-xs
        %ul.nav.navbar-nav
          %li.nav-item.active
            =link_to "Home", home_path
          %li.nav-item
            =link_to "Services", services_path
          %li.nav-item
            =link_to "About", about_path
          %li.nav-item
            =link_to "Blog", "/blog"
          %li.nav-item
            =link_to "Shop", shop_path
  .container-fluid.l-social.text-center
    %ul.list-inline
      %li.list-inline-item
        =link_to "Facebook", "#"
      %li.list-inline-item
        =link_to "Twitter", "#"
      %li.list-inline-item
        =link_to "Instagram", "#"
    %ul.list-inline
      %li.list-inline-item
        %small
          %strong Ph: 777-777-7777
      %li.list-inline-item
        %small &nbsp;|&nbsp;
      %li.list-inline-item
        %small
          %strong Email: info@niche-ie.com